name: CD to GKE

on:
  push:
    branches:
      - develop  # Adjust this to your default branch
jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install 7-Zip
      run: choco install -y 7zip 

    - name: Install Python 3.9
      run: choco install -y python --version 3.9.0

    - name: Download Google Cloud SDK
      run: Invoke-WebRequest -Uri "https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-353.0.0-windows-x86_64.zip" -OutFile "gcloud-sdk.zip"

    - name: Unzip Google Cloud SDK
      run: 7z x gcloud-sdk.zip -oC:\gcloud-sdk -y
  
    - name: Add gcloud to PATH
      run: |
        echo C:\gcloud-sdk\google-cloud-sdk\bin | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
        echo C:\Python39 | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8


    - id: 'auth'
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Authenticate Docker to GCR
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        set IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app:${{ github.sha }}
        echo %IMAGE_NAME%
        docker build -t %IMAGE_NAME% .
        docker push %IMAGE_NAME%

    - name: Deploy to GKE
      env:
        KUBECONFIG: /home/runner/.kube/config
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --zone ${{ secrets.GKE_ZONE }}
        kubectl set image deployment/my-app my-app=%IMAGE_NAME%
